### ISSUE TITLE
KL loss function

### ISSUE THREAD

**Issue by Ying156209** [ChenFengYe/motion-latent-diffusion#18]
Hi, I find there are only feature MAE and joints MAE losses.  Where does KL call at this stage?   https://github.com/ChenFengYe/motion-latent-diffusion/blob/af507c479d771f62a058b5b6abb51276b36d6c6d/mld/models/losses/mld.py#L100
 Thanks!

**Comment by ChenFengYe** [comment]
Ohhhh... Thanks for pointing that out. We are sorry about this mistake. This bug happens when we re-organize our new configuration for release. We have fixed this part now.

https://github.com/ChenFengYe/motion-latent-diffusion/blob/719c219bd059e14f84f2571ab6975855ede0d819/mld/models/losses/mld.py#L105
